[package]
name = "rpn"
version = "0.1.0"
edition = "2021"

[lib]
name = "rpn_lib"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
criterion = "0.3"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

# For criterion testing
[[bench]]
name = "benchmark"
harness = false